from . import meat_waste_report
from . import buenos_aires_tonnages_report
from . import purchase_orders_ebi_report
from . import private_companies_report
from . import communities_waste_report
from . import recycling_on_route_report
from . import waste_report
from . import districts_tonnages_report
from . import non_recyclable_waste_report
from . import waste_disposition_report
from . import waste_percentage_report
