import type { Metadata } from "next";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/system";
import Providers from "@/components/Providers";

export const metadata: Metadata = {
  title: "Control de Riesgos - MPZ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="font-sans">
        <Providers>
          <NextUIProvider>
            {children}
          </NextUIProvider>
        </Providers>
      </body>
    </html>
  );
}
