SELECT
    'ACTUAL' AS ORIGEN,
    r.NUM_RECIBO,
    r.FEC_ENVIO,
    r.CEDULA,
    r.NOM_CUENTA,
    d.PERIODO,
    d.COD_SER_EX,
    d.DES_SER_EX AS CONCEPTO,
    d.MON_CANCEL,
    d.MON_INTERE,
    r.MON_RECIBO
FROM DEC.CUF_RECIBO r
INNER JOIN DEC.CUF_TRARED d
    ON d.NUM_RECIBO = r.NUM_RECIBO
WHERE r.CEDULA = :cedula

UNION ALL

SELECT
    'HISTORICO' AS ORIGEN,
    r.NUM_RECIBO,
    r.FEC_ENVIO,
    r.CEDULA,
    r.NOM_CUENTA,
    d.PERIODO,
    d.COD_SER_EX,
    d.DES_SER_EX AS CONCEPTO,
    d.MON_CANCEL,
    d.MON_INTERE,
    r.MON_RECIBO
FROM DEC.CUF_RECHIS r
INNER JOIN DEC.CUF_TREDHI d
    ON d.NUM_RECIBO = r.NUM_RECIBO
WHERE r.CEDULA = :cedula

ORDER BY FEC_ENVIO DESC, PERIODO DESC