# -*- coding: utf-8 -*-
{
    "name": "Parking Meters",
    "version": "1.0",
    "description": "Parking Meters",
    "summary": "Parking Meters",
    "author": "Municipalidad de Pérez Zeledón",
    "category": "Administration",
    "depends": ["base", "web", "notifications_mpz", "online_payments"],
    "data": [
        "data/ir_config_parameter_data.xml",
        "data/sequences.xml",
        "data/ir_cron_surcharge.xml",
        "data/ir_cron_data.xml",
        "security/res_groups.xml",
        "security/ir_cashier_user_access.xml",
        "security/ir_admin_user_access.xml",
        "security/ir_ti_user_access.xml",
        "security/ir_officer_user_access.xml",
        "security/ir_web_user_access.xml",
        "views/user/view_tree.xml",
        "views/user/view_kanban.xml",
        "views/user/view_form.xml",
        "views/user/actions.xml",
        "views/article/view_tree.xml",
        "views/article/view_form.xml",
        "views/article/actions.xml",
        "views/brand/view_tree.xml",
        "views/brand/view_form.xml",
        "views/brand/actions.xml",
        "views/clause/view_tree.xml",
        "views/clause/view_form.xml",
        "views/clause/actions.xml",
        "views/color/view_tree.xml",
        "views/color/view_form.xml",
        "views/color/actions.xml",
        "views/plate_detail/view_tree.xml",
        "views/plate_detail/view_form.xml",
        "views/plate_detail/actions.xml",
        "views/infraction_price/view_tree.xml",
        "views/infraction_price/view_form.xml",
        "views/infraction_price/actions.xml",
        "views/infraction_state/view_tree.xml",
        "views/infraction_state/view_form.xml",
        "views/infraction_state/actions.xml",
        "views/plate_type/view_tree.xml",
        "views/plate_type/view_form.xml",
        "views/plate_type/actions.xml",
        "views/vehicle_type/view_tree.xml",
        "views/vehicle_type/view_form.xml",
        "views/vehicle_type/actions.xml",
        "views/parameter/view_tree.xml",
        "views/parameter/view_form.xml",
        "views/parameter/actions.xml",
        "views/range_infraction/view_tree.xml",
        "views/range_infraction/view_form.xml",
        "views/range_infraction/actions.xml",
        "views/parking_rate/view_tree.xml",
        "views/parking_rate/view_form.xml",
        "views/parking_rate/actions.xml",
        "views/infraction_export/view_form.xml",
        "views/infraction_export/actions.xml",
        "views/infraction_import/view_form.xml",
        "views/infraction_import/actions.xml",
        "views/infractions_wizard/view_form.xml",
        "views/infraction/view_tree.xml",
        "views/infraction/view_form.xml",
        "views/infraction/actions.xml",
        "views/infraction/map_modal/view_form.xml",
        "views/infraction/image_modal/view_form.xml",
        "views/infraction/confirmation_modal/view_form.xml",
        "views/infraction/payment_modal/view_form.xml",
        "views/infraction/reprint_modal/view_form.xml",
        "views/parking_time/view_tree.xml",
        "views/parking_time/view_form.xml",
        "views/parking_time/actions.xml",
        
        "views/menu.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "parking_meters/static/src/js/print_button.js", 
            "parking_meters/static/src/css/style.css",
            ],
    },
    "application": True,
    "installable": True,
    "auto_install": False,
    "license": "LGPL-3",
}
