from . import meat_waste_wizard
from . import buenos_aires_tonnages_wizard
from . import purchase_orders_ebi_wizard
from . import recycling_on_route_wizard
from . import private_companies_wizard
from . import communities_waste_wizard
from . import waste_wizard
from . import districts_tonnages_wizard
from . import non_recyclable_waste_wizard
from . import waste_disposition_wizard
from . import waste_percentage_wizard
