# -*- coding: utf-8 -*-
from . import res_user
from . import article
from . import brand
from . import clause
from . import color
from . import plate_detail
from . import infraction_price
from . import infraction_state
from . import plate_type
from . import vehicle_type
from . import infraction
from . import image
from . import ir_config_parameter
from . import range_infraction
from . import parking_rate
from . import parking_time
from . import infraction_export
from . import infraction_import
from . import infractions_wizard
from . import payment_type
