from . import comparative_fuel_cost_report
from . import fuel_consumption_by_plate_report
from . import fuel_cost_report
from . import fuel_cost_route_non_recyclable_report
from . import fuel_efficiency_report
from . import fuel_purchase_orders_report
from . import km_per_route_report
from . import km_route_non_recyclable_report
from . import km_traveled_report
